import "../../../global.css";
import Header from "../../Header/index.jsx";

export const Projects = () => {
  return (
    <div>
        <div>Projects</div>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat reprehenderit amet sunt deleniti aperiam alias nemo quis autem provident expedita ea molestias, nesciunt, sed impedit architecto odit? Reprehenderit optio corrupti veniam explicabo eaque impedit ab quae incidunt. Nobis praesentium, ipsam harum tempora doloremque dicta rerum, quae amet et optio, maiores nisi hic? Quod, deserunt tenetur. Dolor in illum esse optio, nisi, magni voluptas saepe perspiciatis totam odit deleniti porro! Numquam consequuntur incidunt nemo blanditiis magni, quidem sed dicta quod, temporibus amet distinctio quasi non maiores quis magnam? Accusantium excepturi adipisci nemo vel sint quasi deserunt nulla assumenda, quam, exercitationem minus.</div>
        <br />
        
    </div>
  )
}
